app/urls.py
from django.urls import path
from app import views 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordChangeForm, MyPasswordResetForm,MySetPasswordForm
from .views import SearchResultsView


# from django.conf import settings

urlpatterns = [
    # path('', views.home),
     path('',views.ProductView.as_view(),name="home"),
     path('product-detail/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
     path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
     path('cart/',views.show_cart,name='showcart'),
     path('category/',views.category,name='category'),

     path('pluscart/',views.plus_cart),
     path('minuscart/',views.minus_cart),
     path('removecart/',views.remove_cart),

     path('plussize/',views.plus_size),
     path('minussize/',views.minus_size),

     path("search/", SearchResultsView.as_view(), name="search_results"),

     path('buy/', views.buy_now, name='buy-now'),
     path('profile/', views.ProfileView.as_view(), name='profile'),
     path('address/', views.address, name='address'),
     path('orders/', views.orders, name='orders'),
     path('men/', views.men, name='men'),
     path('men/<slug:data>', views.men, name='mendata'),
     path('women/', views.women, name='women'),
     path('women/<slug:data>', views.women, name='womendata'),
     path('kid/', views.kid, name='kid'),
     path('kid/<slug:data>', views.kid, name='kiddata'),

     path('checkout/', views.checkout, name='checkout'),
     path('paymentnew/', views.payment, name='payment'),

     path('paymentdone/', views.payment_done, name='paymentdone'),

     path('contactus/',views.contactus,name='contactus'),
     path('aboutus/',views.aboutus,name='aboutus'),

     #authentication
     path('accounts/login/', auth_views.LoginView.as_view
         (template_name='app/login.html', authentication_form=LoginForm), name='login'),

     path('logout/',auth_views.LogoutView.as_view(next_page='login'),name='logout'),

     path('passwordchange/',auth_views.PasswordChangeView.as_view
         (template_name='app/passwordchange.html',form_class=MyPasswordChangeForm, 
          success_url='/passwordchangedone/'),name='passwordchange'),

     path('passwordchangedone/', auth_views.PasswordChangeView.as_view
          (template_name='app/passwordchangedone.html'),name='passwordchangedone'),

     path('password-reset/',auth_views.PasswordResetView.as_view
          (template_name='app/password_reset.html',
          form_class=MyPasswordResetForm),name='password_reset'),

     path('password-reset/done/',auth_views.PasswordResetDoneView.as_view
          (template_name='app/password_reset_done.html'),
         name='password_reset_done'),

     path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view
          (template_name='app/password_reset_Confirm.html',
         form_class=MySetPasswordForm),name='password_reset_confirm'),

     path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view
          (template_name='app/password_reset_complete.html'),
         name='password_reset_complete'),

     path('registration/',views.CustomerRegistrationView.as_view(), name="customerregistration"),

     #path('dwld_pdf/',views.down_pdf,name="dwld_pdf"),
     #path('download_pdf',views.dwnld_pdf,name='download_pdf'),
     path('generate-pdf/', views.generate_pdf, name='generate_pdf'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

efvs/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('delivery.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator
# Create your models here.

# class User(models.Model):
#     file = models.FileField() 


STATE_CHOICES = (
    ('Punjab','Punjab'),
    ('Bihar','Bihar'),
    ('Gujarat','Gujarat'),
    ('Karnataka','Karnataka'),
    ('Goa','Goa'),
)
class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    locality = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    zipcode = models.IntegerField()
    state = models.CharField(choices=STATE_CHOICES, max_length=50)

    def __str__(self):
        return str(self.id)
    
CATEGORY_CHOICES = (
    ('M', 'Men'),
    ('W', 'Women'),
    ('K','Kids'),
)

class Product(models.Model):
    title = models.CharField(max_length=100)
    selling_price = models.FloatField()
    discounted_price = models.FloatField()
    description = models.TextField() 
    brand = models.CharField(max_length=100)
    category = models.CharField( choices=CATEGORY_CHOICES,
                                max_length=2)
    product_image = models.ImageField(upload_to='producting')
    
    
    def __str__(self):
        return str(self.id)
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
    @property
    def total_cost(self):
        return self.quantity * self.product.discounted_price

STATUS_CHOICES = (
    ('Accepted','Accepted'),
    ('Packed','Packed'),
    ('On The Way','On The Way'),
    ('Delivered','Delivered'),
    ('Cancel','Cancel')
)

# class Payment(models.Model):
#     user = models.ForeignKey(User,on_delete=models.CASCADE)
#     amount = models.FloatField()
#     razorpay_order_id = models.CharField(max_length=100,blank=True,null=True)
#     razorpay_payment_status = models.CharField(max_length=100,blank=True,null=True)
#     razorpay_payment_id = models.CharField(max_length=100,blank=True,null=True)
#     paid = models.BooleanField(default=False)

class OrderPlaced(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.PositiveIntegerField(default=1)
    ordered_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50,
                              choices=STATUS_CHOICES,default='Pending')

    @property
    def total_cost(self):
        return self.quantity * self.product.discounted_price + 70  
    
class Contact(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return str(self.id)

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField,PasswordChangeForm,PasswordResetForm,SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _
from django.contrib.auth import password_validation
from .models import Customer
from .models import Contact
# from .models import Product


class CustomerRegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', 
                                widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm Password', 
                                widget=forms.PasswordInput(attrs={'class':'form-control'}))
    email = forms.CharField(required=True, 
                                widget=forms.EmailInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        labels = {'email': 'Email'}
        widgets = {'username': forms.TextInput(attrs={'class':'form-control'})}


    def clean_email(self):
        data = self.cleaned_data['email']
        domain = data.split('@')[1]
        domain_list = ["gmail.com", "yahoo.com", "hotmail.com",]
        if domain not in domain_list:
            raise forms.ValidationError("Please enter an Email Address with a valid domain")
        return data
    
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs=
                                                    {'autofocus':True,'class':'form-control'}))
    password = forms.CharField(label=_("Password"),
                               strip=False,
                               widget=forms.PasswordInput(attrs=
                                                    {'autocomplete':'current-password','class':'form-control'}))
    
class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Old Password"),strip=False,widget=forms.PasswordInput(attrs=
                                                                                                  {'autocomplete': 'current-password','autofocus':True,'class':'form-control'}))
    new_password1 = forms.CharField(label=_("New Password"),strip=False,widget=forms.PasswordInput(attrs=
                                                                           {'autocomplete':'new-password','class':'form-control'}),
                                                                            help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm New Password"),strip=False,widget=forms.PasswordInput(attrs=
                                                                           {'autocomplete':'new-password','class':'form-control'}))
    
class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label=("Email"),max_length=254, widget=forms.EmailInput(attrs={'autocomplete':'email',
    'class':'form-control'}))

class MySetPasswordForm(SetPasswordForm):
     new_password1 = forms.CharField(label=_("New Password"),
                                    strip=False,widget=forms.PasswordInput(attrs=
                                                                           {'autocomplete':'new-password',
                                                                            'class':'form-control'}),
    help_text=password_validation.password_validators_help_text_html())
     new_password2 = forms.CharField(label=_("Confirm New Password"),
                                    strip=False,widget=forms.PasswordInput(attrs=
                                                                           {'autocomplete':'new-password','class':'form-control'}))
     
class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name','locality','city','state','zipcode']
        widgets = {'name':forms.TextInput(attrs={'class':'form-control'}),
                   'locality':forms.TextInput(attrs={'class':'form-control'}),
                   'city':forms.TextInput(attrs={'class':'form-control'}),
                   'state':forms.Select(attrs={'class':'form-control'}),
                   'zipcode':forms.NumberInput(attrs={'class':'form-control'})}
        

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        

app/templates/app/addtocart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <h1 class="text-center mb-5">Shopping Cart</h1>
  <div class="col-sm-8">
  <div class="card">
   <div class="card-body">
    <h3>Cart</h3>
    {% for cart in carts %}
    <hr>
    <div class="row">
     <div class="col-sm-3 text-center align-self-center">
      <img src="{{cart.product.product_image.url}}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"> </div>
     <div class="col-sm-9">
      <div>
       <h5>{{cart.product.title}}</h5>
       <p class="mb-2 text-muted small">
        {{cart.product.description}}
       </p>
       <div class="my-3">
        <label for="quantity">Quantity:</label>
        <a class="minus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">{{cart.quantity}}</span>
        <a class="plus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-plus-square fa-lg"></i></a>
       </div>
       <div class="my-3">
        <label for="size">Size:</label>
        <a class="minus-size btn" pid="{{cart.product.id}}"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="size">{{cart.size}}</span>
        <a class="plus-size btn" pid="{{cart.product.id}}"><i class="fas fa-plus-square fa-lg"></i></a>
       </div> 
       <div class="d-flex justify-content-between">
        <a href="#" class="btn btn-sm btn-secondary mr-3 remove-cart" pid="{{cart.product.id}}">
          Remove item </a>
        <p class="mb-0">
          <span>
          <strong>Rs. {{cart.product.discounted_price}}</strong>
        </span></p>
       </div>
      </div>
     </div>
    </div>
    {% endfor %}
    
   </div>
   </div>
  </div>

  <div class="col-sm-4">
   <div class="card">
    <div class="card-body">
      <h3>The Total Amount of</h3>
      <ul class="list-group">
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
        Amount<span>Rs. <span id="amount">{{amount}}</span></span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center px-0">
        Shipping<span>Rs. 70.00</span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total</strong> <small>(including VAT)</small>
         </div>
         <span><strong>Rs. <strong id="totalamount">{{totalamount}}</strong></strong></span>
       </li>
      </ul>
      <div class="d-grid"><a href="{% url 'checkout' %}" class="btn btn-primary">Place Order</a></div>
    </div>
   </div>
  </div>
  
 </div>
</div>

{% endblock main-content %}

app/templates/app/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!--Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css' %}">

    <!--FontAwesome CSS-->
    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}">

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    
    <style>
     ul li a{
    text-decoration: none;
    color: black;
    padding: 5px 20px;
    transition: background-color .5s;
    }
    ul li a:hover{
        background-color: rgba(214, 124, 124, 0.966);
        color: white;
    }


    </style>

    <title>Elite Footwear | {% block title %} {% endblock title %} </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <div class="container">
      <img src="{% static 'app/images/header/h6.png' %}" style="height: 60px;">&nbsp; &nbsp; &nbsp; 
       <a class="navbar-brand" href="/" style="font-family: Apple Chancery,cursive;">Elite Footwear</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
             <a class="nav-link active" aria-current="page" href="/">Home</a>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link text-white" href="{% url 'category' %}"   aria-expanded="false">
               Category
             </a>
             <!-- <ul class="dropdown-menu" aria-labelledby="electronicsDropdown">
               <li><a class="dropdown-item" href="{% url 'men' %}">Men</a></li>
               <li><a class="dropdown-item" href="{% url 'women' %}">Women</a></li>
               <li><a class="dropdown-item" href="{% url 'kid' %}">Kids</a></li>
             </ul> -->
           </li>
           <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'contactus' %}">Contact Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'aboutus' %}">About Us</a>
          </li>
         </ul>
         <form class="d-flex" action="{% url 'search_results' %}" method="get">
           <input class="form-control me-2" name="q" type="text" placeholder="Search" aria-label="Search">
           <button class="btn btn-warning" type="submit"><i class="fa fa-search"></i></button>
         </form>
         <div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
           <li class="nav-item dropdown mx-2">
              <a class="nav-link dropdown-toggle text-white" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user-alt" style='font-size:30px'></i>&nbsp;{{request.user.username|capfirst}}
              </a>
              <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'orders' %}">Orders</a></li>
                <li><a class="dropdown-item" href="{% url 'passwordchange' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
              </ul>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'showcart' %}" class="nav-link text-white">
              <span class="badge bg-danger">{{totalitem}}</span>
               Cart&nbsp;<i class="fa fa-shopping-cart" style='font-size:30px'></i> </a>
            </li>
            {% else %}
            <li class="nav-item mx-2">
             <a href="{% url 'login' %}" class="nav-link text-white">Login</a>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'customerregistration' %}" class="nav-link text-white">Registration</a>
            </li>
            {% endif %}
          </ul>
         </div>
       </div>
     </div>
    </nav>
    {% block banner_slider %} {% endblock banner_slider %}
    {% block livesale %} {% endblock livesale %}
    {% block main-content %} {% endblock main-content %}
    {% block payment-gateway %} {% endblock payment-gateway %}
    
    <!-- Start Footer -->
    <footer class="container-fluid bg-dark text-center p-2 mt-5">
        <marquee><small class="text-white">Copyright &copy; 2023 || Elite Footwear Virtual Store || </small></marquee>
        
    </footer> <!-- End Footer -->

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'app/js/all.min.js' %}"></script>
    <script src="{% static 'app/js/myscript.js' %}"></script>
  </body>
</html>

app/templates/app/buynow.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
    <div class="row">
     <h1 class="text-center mb-5">Shopping Cart</h1>
     <div class="col-sm-8">
     <div class="card">
      <div class="card-body">
       <h3>Cart</h3>
       {% for cart in carts %}
       <hr>
       <div class="row">
        <div class="col-sm-3 text-center align-self-center">
         <img src="{{cart.product.product_image.url}}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"> </div>
        <div class="col-sm-9">
         <div>
          <h5>{{cart.product.title}}</h5>
          <p class="mb-2 text-muted small">
           {{cart.product.description}}
          </p>
          <div class="my-3">
           <label for="quantity">Quantity:</label>
           <a class="minus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-minus-square fa-lg"></i></a>
             <span id="quantity">{{cart.quantity}}</span>
           <a class="plus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-plus-square fa-lg"></i></a>
          </div>
          <div class="my-3">
           <label for="size">Size:</label>
           <a class="minus-size btn" pid="{{cart.product.id}}"><i class="fas fa-minus-square fa-lg"></i></a>
             <span id="size">{{cart.size}}</span>
           <a class="plus-size btn" pid="{{cart.product.id}}"><i class="fas fa-plus-square fa-lg"></i></a>
          </div> 
          <div class="d-flex justify-content-between">
           <a href="#" class="btn btn-sm btn-secondary mr-3 remove-cart" pid="{{cart.product.id}}">
             Remove item </a>
           <p class="mb-0">
             <span>
             <strong>Rs. {{cart.product.discounted_price}}</strong>
           </span></p>
          </div>
         </div>
        </div>
       </div>
       {% endfor %}
       
      </div>
      </div>
     </div>
   
     <div class="col-sm-4">
      <div class="card">
       <div class="card-body">
         <h3>The Total Amount of</h3>
         <ul class="list-group">
          <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
           Amount<span>Rs. <span id="amount">{{amount}}</span></span></li>
          <li class="list-group-item d-flex justify-content-between align-items-center px-0">
           Shipping<span>Rs. 70.00</span></li>
          <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
           <div>
              <strong>Total</strong> <small>(including VAT)</small>
            </div>
            <span><strong>Rs. <strong id="totalamount">{{totalamount}}</strong></strong></span>
          </li>
         </ul>
         <div class="d-grid"><a href="{% url 'checkout' %}" class="btn btn-primary">Place Order</a></div>
       </div>
      </div>
     </div>
     
    </div>
   </div>
{% endblock main-content %}

app/templates/app/contactus.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Contact Us{% endblock title %}
{% block main-content %}
<style>
  form { max-width:420px; }

.feedback-input {
  color:black;
  font-family: Helvetica, Arial, sans-serif;
  font-weight:500;
  font-size: 18px;
  border-radius: 5px;
  line-height: px;
  background-color: transparent;
  border:2px solid #CC6666;
  transition: all 0.3s;
  padding: 13px;
  margin-bottom: 15px;
  width:100%;
  box-sizing: border-box;
  outline:0;
}

.feedback-input:focus { border:2px solid #CC4949; }

textarea {
  height: 150px;
  line-height: 150%;
  resize:vertical;
}

[type="submit"] {
  font-family: 'Montserrat', Arial, Helvetica, sans-serif;
  width: 100%;
  background:#CC6666;
  border-radius:5px;
  border:0;
  cursor:pointer;
  color:white;
  font-size:24px;
  padding-top:10px;
  padding-bottom:10px;
  transition: all 0.3s;
  margin-top:-4px;
  font-weight:700;
}
[type="submit"]:hover { background:#CC4949; }
</style>
<center>
<form action="" method="post" style="border: 25px;">
  {% csrf_token %}
  <!-- <input type="hidden" name="csrfmiddlewaretoken" value="yTF5g7ceTgkwsOimKxZpuV10DG4a1TWFwQ60pneu047lPvu6kTAlNYPfYEC9G8jq"> -->
  <tr>
    <th>
        <label for="id_name"></label>
    </th>
    <td>
        <input type="text" name="name" maxlength="40" required id="id_name" class="feedback-input" placeholder="Enter your Name">
    </td>
</tr>
<tr>
  <tr>
      <th>
          <label for="id_email"></label>
      </th>
      <td>
          <input type="email" name="email" maxlength="254" required id="id_email" class="feedback-input" placeholder="Enter your Email">
      </td>
  </tr>
  <tr>
      <th>
          <label for="id_subject"></label>
      </th>
      <td>
          <input type="text" name="subject" maxlength="255" required id="id_subject" class="feedback-input" placeholder="Enter Subject">
      </td>
  </tr>
  <tr>
      <th>
          <label for="id_message"></label>
      </th>
      <td>
          <textarea name="message" cols="40" rows="10" required id="id_message" class="feedback-input" placeholder="Enter your Message"></textarea>
      </td>
  </tr>
  <input type="submit" value="Submit">
</form></center>
{% endblock main-content %}

app/templates/app/customerregistration.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Customer Registration{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Customer Registration</h3>
   <hr>
 
   <form action="" method="post" novalidate class="shadow p-5">
      {% if messages %}
       {% for messages in messages %}
         <p {% if message.tags %} class="alert alert-{{message.tags}} mb-3"
         {% endif %}>
           <h4 style="color: green;">{{messages}}</h4>
         </p>
       {% endfor %}
      {% endif %}
    {% csrf_token %}  
    {% for fm in form %}
    <div class="form-group mb-3">
      {{fm.label_tag}} {{fm}} 
      <small class="text-danger">
         {{fm.errors|striptags}}
      </small>
    </div>
    {% endfor %}
    <input type="submit" value="Submit"
    class="btn btn-primary">
    <br>
    <div class="text-center text-primary fw-bold">
      <small>
         Existing User ? 
         <a href="{% url 'login' %}" class="text-danger">
            Login Now
         </a>
      </small>
    </div>
    {% if form.non_field_errors %}
     {% for error in form.non_field_errors %}
      <p class="alert alert-danger my-3">
         {{error}}
      </p>
     {% endfor %}
    {% endif %}
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/emptycart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Empty Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <h3 class="text-center">You have no product in Your Cart</h3>
  <div class="text-center">
    <img src="{% static 'app/images/emptycart.png' %}"
    alt="" class="img-fluid img-thumbnail w-25">
  </div>
 </div>
</div>  
{% endblock main-content %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Login</h3>
   <hr>
   <form action="" method="post" novalidate class="shadow p-5">
    {% csrf_token %}
    {% for fm in form %}
    <div class="form-group">
        {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small><br>
    </div>
    {% endfor %}
    <small>
        <a href="{% url 'password_reset' %}">Forget Password ?</a>
    </small><br>
    <input type="submit" class="btn btn-primary mt-4" value="Login">
    <br>
    <div class="text-center text-primary fe-bold">
        <small>New to Elite Footwear ? 
            <a href="{% url 'customerregistration' %}" class="text-danger">
                Create an Account
            </a>
        </small>
    </div>
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}